{
    "model_class": "Job",
    "id": "2f18fe533fe210b4",
    "state": "error",
    "exit_code": 1,
    "update_time": "2024-04-02T06:28:41.521786",
    "create_time": "2024-04-02T06:28:30.960743",
    "galaxy_version": "23.1",
    "command_version": "",
    "copied_from_job_id": null,
    "tool_id": "toolshed.g2.bx.psu.edu/repos/devteam/fastq_groomer/fastq_groomer/1.1.5",
    "history_id": "3c2ea82547e21343",
    "external_id": "gxy-4pd6c",
    "command_line": "gx-fastq-groomer '/galaxy/server/database/objects/d/f/0/dataset_df0d1f35-b47a-4786-989f-8456ab0357fa.dat' sanger '/galaxy/server/database/objects/c/5/9/dataset_c598d398-4ee1-4c62-a394-429a22002ce6.dat' sanger ascii summarize_input --no-fix-id",
    "traceback": null,
    "params": {
        "__input_ext": "\"fastq\"",
        "dbkey": "\"?\"",
        "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",
        "options_type": "{\"__current_case__\": 1, \"fix_id\": false, \"force_quality_encoding\": \"ascii\", \"options_type_selector\": \"advanced\", \"output_type\": \"sanger\", \"summarize_input\": \"summarize_input\"}",
        "input_type": "\"sanger\""
    },
    "inputs": {
        "input_file": {
            "id": "543fd8a23230e601",
            "src": "hda",
            "uuid": "df0d1f35-b47a-4786-989f-8456ab0357fa"
        }
    },
    "outputs": {
        "output_file": {
            "id": "2f18fe533fe210b4",
            "src": "hda",
            "uuid": "c598d398-4ee1-4c62-a394-429a22002ce6"
        }
    },
    "output_collections": {},
    "tool_stdout": "There was an error reading your input file. Your input file is likely malformed.\nIt is suggested that you double-check your original input file for errors -- helpful information for this purpose has been provided below.\nHowever, if you think that you have encountered an actual error with this tool, please do tell us by using the bug reporting mechanism.\n\nThe reported error is: 'Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).'.\nThe error occurred at the start of your file and no valid FASTQ reads were found.\nThe error in your file occurs between lines '1' and '3', which corresponds to byte-offsets '0' and '33', and contains the text (33 of 33 bytes shown):\n\n@FAKE-1\nACGTACGTAC\n+invalid line\n\n",
    "tool_stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/gx-fastq-groomer\", line 10, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py\", line 99, in main\n    Groomer().run()\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py\", line 48, in run\n    for read_count, fastq_read in enumerate(reader):\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 683, in __iter__\n    yield next(self)\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 742, in __next__\n    raise e\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 724, in __next__\n    block = super(fastqVerboseErrorReader, self).__next__()\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 621, in __next__\n    self._read_fastq_sequence(rval, id_line)\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 666, in _read_fastq_sequence\n    raise fastqFormatError(\ngalaxy_utils.sequence.fastq.fastqFormatError: Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).\n",
    "job_stdout": "",
    "job_stderr": "",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/gx-fastq-groomer\", line 10, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py\", line 99, in main\n    Groomer().run()\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/scripts/fastq_groomer.py\", line 48, in run\n    for read_count, fastq_read in enumerate(reader):\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 683, in __iter__\n    yield next(self)\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 742, in __next__\n    raise e\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 724, in __next__\n    block = super(fastqVerboseErrorReader, self).__next__()\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 621, in __next__\n    self._read_fastq_sequence(rval, id_line)\n  File \"/usr/local/lib/python3.8/site-packages/galaxy_utils/sequence/fastq.py\", line 666, in _read_fastq_sequence\n    raise fastqFormatError(\ngalaxy_utils.sequence.fastq.fastqFormatError: Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).\n",
    "stdout": "There was an error reading your input file. Your input file is likely malformed.\nIt is suggested that you double-check your original input file for errors -- helpful information for this purpose has been provided below.\nHowever, if you think that you have encountered an actual error with this tool, please do tell us by using the bug reporting mechanism.\n\nThe reported error is: 'Invalid FASTQ file: quality score identifier (+invalid line)                         does not match sequence identifier (@FAKE-1).'.\nThe error occurred at the start of your file and no valid FASTQ reads were found.\nThe error in your file occurs between lines '1' and '3', which corresponds to byte-offsets '0' and '33', and contains the text (33 of 33 bytes shown):\n\n@FAKE-1\nACGTACGTAC\n+invalid line\n\n",
    "job_messages": [],
    "dependencies": [],
    "user_email": "tests@fake.org",
    "job_metrics": [
        {
            "title": "Job Runtime (Wall Clock)",
            "value": "0 seconds",
            "plugin": "core",
            "name": "runtime_seconds",
            "raw_value": "0E-7"
        },
        {
            "title": "Job End Time",
            "value": "2024-04-02 06:28:32",
            "plugin": "core",
            "name": "end_epoch",
            "raw_value": "1712039312.0000000"
        },
        {
            "title": "Job Start Time",
            "value": "2024-04-02 06:28:32",
            "plugin": "core",
            "name": "start_epoch",
            "raw_value": "1712039312.0000000"
        },
        {
            "title": "Memory Allocated (MB)",
            "value": "8160",
            "plugin": "core",
            "name": "galaxy_memory_mb",
            "raw_value": "8160.0000000"
        },
        {
            "title": "Cores Allocated",
            "value": "1",
            "plugin": "core",
            "name": "galaxy_slots",
            "raw_value": "1.0000000"
        }
    ]
}
